image: acryldata/datahub-ingestion-base:latest

tasks:
  - name: gradle commands to pull in most of dependencies
    command: |
      ./gradlew :datahub-web-react:yarnLintFix
      ./gradlew :datahub-frontend:dist -x yarnTest -x yarnLint
      ./gradlew :metadata-service:war:build
  - name: python commands to pull in most python dependencies
    command: |
      python3 -m pip install --upgrade pip wheel setuptools
      python3 -m pip uninstall datahub acryl-datahub || true
      python3 -m pip install --upgrade acryl-datahub
      datahub version

vscode:
  extensions:
    - ms-python.python