
tasks:
  - name: gradle commands to pull in most of dependencies
    command: |
      ./gradlew :datahub-web-react:yarnLintFix
      ./gradlew :datahub-frontend:dist -x yarnTest -x yarnLint
      ./gradlew :metadata-service:war:build
  - name: python commands to pull in most python dependencies
    command: |
      cd metadata-ingestion
      python3 -m venv venv
      source venv/bin/activate
      pip install -e '.[dev]'

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - ms-python.python